### ISSUE TITLE
Add a "Days remaining" counter on the public dashboard page

### ISSUE THREAD

**Issue by justdave** [justdave/nslodge-wp-customizations#6]

**Comment by isayuh** [comment]
On the main page with the graph, you just want a counter pertaining to  the days left until these dates, correct?
"Elections should be scheduled by March 31st.
Makeup elections should be completed by April 30th." 

Should this be 2 counters, or one counter that switches to makeup elections after the deadline of March 31st has passed? Thanks!

**Comment by justdave** [comment]
One that switches when the date is past, probably. Seems weird to have it now since both dates have passed though.

**Comment by justdave** [comment]
Informally we've said we're taking elections through June, because so many didn't get them done, maybe we should just say that.

**Comment by isayuh** [comment]
ok, are they the same dates each year? Or do they change? I could work on a counter that resets and displays next year's dates if they stay constant

**Comment by justdave** [comment]
Yeah, same every year. Election season starts November 1, maybe have it count down the days until the next season starts once it ends? (Do you have your election teams trained yet?) Might be better to wait until September or so to put that up though.

**Comment by isayuh** [comment]
Ok, I can work on it and we can push it in September
